num1 = int(input("Enter your first number: "))
num2 = int(input("Enter your second number: "))
num3 = int(input("Enter your thirth number: "))
num4 = int(input("Enter your fourth number: "))
print(num1+num2 - (num3*num4))